build:
  version: "1.0"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    #url: jdbc:h2:mem:accountsdb
    username: root
    password: root
  config:
    import: "optional:configserver:http://configserver:8071/"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/

accounts:
  message: "Hey, welcome to EazyBank accounts related webhook APIs"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}f83ac5a34ba5f4657ae8e863c063c1b69efb4d23d0c431eb134f8d1b3ed0823dee0a4b627d091455b4c6600353a3682c"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
