build:
  version: "2.0"
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/accountsdb
    url: jdbc:h2:mem:accountsdb
    username: root
    password: root
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA LeadINGF"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
