build:
  version: "2.0"

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/accountsdb
    url: jdbc:h2:mem:cardsdb
    username: root
    password: root


cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@eazybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267
